"""
test_calibration.py -- pytest suite for calibration_fit.py.

Run with: pytest test_calibration.py -v

Strategy: since no real factory time-study data exists yet, these tests
validate the fitting machinery itself against SYNTHETIC data with a KNOWN
ground truth (generated by calibration_fit.generate_synthetic_batch), which
is exactly what that generator exists for. A real calibration run is not
tested here because there is nothing real to test against -- see
engine_phase1_report.md for what real-data validation will require.
"""
from __future__ import annotations

import math

import numpy as np
import pandas as pd
import pytest

import handling_time as ht
import machine_time as mt
import effective_spm as es
import time_study_loader as tsl
import calibration_fit as cf
import calibration_diagnostics as cd


@pytest.fixture(scope="module")
def tax():
    return ht.load_taxonomy("element_taxonomy.json")


@pytest.fixture(scope="module")
def mcat():
    return mt.load_machine_catalog("machine_classes.csv")


@pytest.fixture(scope="module")
def synthetic_batch(tax, mcat):
    return cf.generate_synthetic_batch(tax, mcat, n_operators=6, n_per_operator=20, seed=7)


@pytest.fixture(scope="module")
def loaded_rows(tax, mcat, synthetic_batch):
    loader = tsl.TimeStudyLoader(tax, mcat)
    batch_for_loader = {k: v for k, v in synthetic_batch.items() if k != "_ground_truth"}
    lr = loader.load_batch_dict(batch_for_loader)
    assert not lr.rejections, f"unexpected rejections: {lr.rejections}"
    return lr.rows


# --------------------------------------------------------------------------
# generate_synthetic_batch
# --------------------------------------------------------------------------

class TestSyntheticGenerator:
    def test_batch_is_schema_valid(self, tax, mcat, synthetic_batch):
        loader = tsl.TimeStudyLoader(tax, mcat)
        batch_for_loader = {k: v for k, v in synthetic_batch.items() if k != "_ground_truth"}
        lr = loader.load_batch_dict(batch_for_loader)
        assert lr.n_observations_seen == len(synthetic_batch["observations"])
        assert not lr.rejections

    def test_batch_flagged_synthetic(self, synthetic_batch):
        assert synthetic_batch["method"] == "SYNTHETIC"
        assert all(o.get("observed_s", 0) > 0 for o in synthetic_batch["observations"])

    def test_observation_kinds_present(self, loaded_rows):
        kinds = {r["kind"] for r in loaded_rows}
        assert kinds <= {"element_observation", "seam_observation", "cycle_observation"}
        assert len(kinds) >= 2, "synthetic generator should produce a mix of observation kinds"

    def test_reproducible_with_seed(self, tax, mcat):
        b1 = cf.generate_synthetic_batch(tax, mcat, n_operators=3, n_per_operator=5, seed=123)
        b2 = cf.generate_synthetic_batch(tax, mcat, n_operators=3, n_per_operator=5, seed=123)
        obs1 = [o["observed_s"] for o in b1["observations"]]
        obs2 = [o["observed_s"] for o in b2["observations"]]
        assert obs1 == obs2


# --------------------------------------------------------------------------
# sensitivity_report / coverage
# --------------------------------------------------------------------------

class TestSensitivity:
    def test_every_symbol_present(self, tax, mcat, loaded_rows):
        p0 = es.MotionParams()
        cov = cf.sensitivity_report(tax, mcat, p0, loaded_rows)
        expected = set(cf.SCOPE1_TAXONOMY_SYMBOLS) | set(cf.MOTIONPARAMS_BOUNDS)
        assert set(cov["symbol"]) == expected

    def test_g_0_sensitive_to_grasp_rows(self, tax, mcat, loaded_rows):
        """g_0 is the grasp-phase intercept used by every element with a
        grasp phase (HAM, HAB, HFC, ...); with a healthy synthetic batch it
        must show up as sensitive on at least a handful of rows."""
        p0 = es.MotionParams()
        cov = cf.sensitivity_report(tax, mcat, p0, loaded_rows)
        row = cov[cov["symbol"] == "g_0"].iloc[0]
        assert row["n_supporting_rows"] > 0

    def test_b_steer_sensitive_to_steer_phase_elements(self, tax, mcat, loaded_rows):
        """b_steer (the global steering-law slope) is used by every element
        whose phase_program includes a 'steer' phase -- not only HGD's
        seam-guide usage but also HFD/HAL/HFC/HTO/HSM, which are all
        element_observation rows. It is legitimately sensitive to BOTH
        observation kinds; this test checks it is sensitive to at least one
        seam_observation row when seam rows are present, not that it is
        seam-exclusive."""
        p0 = es.MotionParams()
        cov = cf.sensitivity_report(tax, mcat, p0, loaded_rows)
        row = cov[cov["symbol"] == "b_steer"].iloc[0]
        has_seam_rows = any(r["kind"] == "seam_observation" for r in loaded_rows)
        if row["n_supporting_rows"] > 0 and has_seam_rows:
            assert "seam_observation" in row["observation_kinds"]

    def test_zero_rows_yields_zero_coverage(self, tax, mcat):
        p0 = es.MotionParams()
        cov = cf.sensitivity_report(tax, mcat, p0, [])
        assert (cov["n_supporting_rows"] == 0).all()


# --------------------------------------------------------------------------
# fit_scope1
# --------------------------------------------------------------------------

class TestFitScope1:
    def test_sparse_rows_keep_defaults(self, tax, mcat):
        """A single observation must never be enough to move a global
        constant off its shipped default -- that is what MIN_OBS_FOR_FIT
        guards against."""
        p0 = es.MotionParams()
        one_row = [{
            "kind": "element_observation", "factory_id": "F1", "operator_id": "OP1",
            "observed_s": 3.0, "method": "SYNTHETIC",
            "detail": {"element_code": "HAG",
                       "params": {"distance_cm": 25.0, "precision_class": "P2"}},
        }]
        outcomes, p_fitted, cov = cf.fit_scope1(tax, mcat, p0, one_row)
        assert all(o.used_default for o in outcomes.values())
        assert p_fitted.as_dict() == p0.as_dict()

    def test_sufficient_rows_move_off_default_toward_truth(self, tax, mcat, loaded_rows):
        """Perturb g_0 in a copy of the taxonomy, generate synthetic rows
        from THAT perturbed taxonomy, then fit scope 1 from the shipped
        (unperturbed) starting point and check the fit recovers something
        closer to the true perturbed value than the shipped default is."""
        import json
        true_g0 = 0.35   # shipped default is smaller; see element_taxonomy.json
        perturbed_raw = json.loads(json.dumps(tax.raw))
        for gp in perturbed_raw["global_parameters"]:
            if gp["symbol"] == "g_0":
                shipped_default = gp["default"]
                gp["default"] = true_g0
        tax_perturbed = ht.Taxonomy(perturbed_raw)

        batch = cf.generate_synthetic_batch(tax_perturbed, mcat, n_operators=5,
                                             n_per_operator=25, seed=99, noise_sigma_log=0.05)
        loader = tsl.TimeStudyLoader(tax, mcat)   # validate against the SHIPPED taxonomy's element signatures
        rows = loader.load_batch_dict({k: v for k, v in batch.items() if k != "_ground_truth"}).rows

        outcomes, p_fitted, cov = cf.fit_scope1(tax, mcat, es.MotionParams(), rows)
        g0_outcome = outcomes["g_0"]
        assert not g0_outcome.used_default, "g_0 should have enough grasp-phase rows to fit"
        dist_before = abs(shipped_default - true_g0)
        dist_after = abs(g0_outcome.fitted_value - true_g0)
        assert dist_after < dist_before, (
            f"fit moved g_0 further from truth: shipped={shipped_default}, "
            f"fitted={g0_outcome.fitted_value}, true={true_g0}"
        )

    def test_fit_respects_plausible_range_bounds(self, tax, mcat, loaded_rows):
        outcomes, p_fitted, cov = cf.fit_scope1(tax, mcat, es.MotionParams(), loaded_rows)
        for sym, outcome in outcomes.items():
            if outcome.used_default:
                continue
            meta = tax.global_meta.get(sym)
            if meta and meta.get("plausible_range"):
                lo, hi = meta["plausible_range"]
                assert lo <= outcome.fitted_value <= hi, f"{sym} fit {outcome.fitted_value} outside [{lo},{hi}]"

    def test_motionparams_bounds_respected(self, mcat, loaded_rows, tax):
        outcomes, p_fitted, cov = cf.fit_scope1(tax, mcat, es.MotionParams(), loaded_rows)
        for field_name, (lo, hi) in cf.MOTIONPARAMS_BOUNDS.items():
            val = getattr(p_fitted, field_name)
            assert lo <= val <= hi, f"{field_name}={val} outside bounds [{lo},{hi}]"


# --------------------------------------------------------------------------
# fit_factory_reference_fabric
# --------------------------------------------------------------------------

class TestFactoryReferenceFabric:
    def test_no_measurements_keeps_global_default(self, loaded_rows):
        out = cf.fit_factory_reference_fabric(loaded_rows)
        for factory_id, syms in out.items():
            for symbol, outcome in syms.items():
                assert outcome.used_default, "synthetic rows carry no environment.measured_* fields"
                assert outcome.fitted_value is None

    def test_sufficient_measurements_are_averaged(self):
        rows = []
        for i in range(6):
            rows.append({
                "factory_id": "FACT-A", "operator_id": "OPX", "kind": "element_observation",
                "observed_s": 1.0,
                "environment": {"measured_B_uNm": 8.0 + i * 0.1},
            })
        out = cf.fit_factory_reference_fabric(rows, min_obs=5)
        outcome = out["FACT-A"]["B_ref"]
        assert not outcome.used_default
        assert outcome.fitted_value == pytest.approx(np.mean([8.0 + i * 0.1 for i in range(6)]))

    def test_different_factories_kept_separate(self):
        rows = [
            {"factory_id": "A", "operator_id": "O1", "kind": "element_observation",
             "observed_s": 1.0, "environment": {"measured_B_uNm": v}}
            for v in [8.0] * 5
        ] + [
            {"factory_id": "B", "operator_id": "O2", "kind": "element_observation",
             "observed_s": 1.0, "environment": {"measured_B_uNm": v}}
            for v in [12.0] * 5
        ]
        out = cf.fit_factory_reference_fabric(rows, min_obs=5)
        assert out["A"]["B_ref"].fitted_value == pytest.approx(8.0)
        assert out["B"]["B_ref"].fitted_value == pytest.approx(12.0)


# --------------------------------------------------------------------------
# fit_operator_gamma
# --------------------------------------------------------------------------

class TestOperatorGamma:
    def test_recovers_operator_ranking(self, tax, mcat):
        """With well-separated true Gamma_skill values and low noise, the
        fitted per-operator multipliers must at least preserve the RANK
        ORDER of the true values -- this is the property line managers
        actually rely on ('who is fast, who is slow'), and a much lower bar
        than exact recovery."""
        true_gamma = {"OP1": 0.85, "OP2": 0.95, "OP3": 1.05, "OP4": 1.15, "OP5": 1.25}
        batch = cf.generate_synthetic_batch(
            tax, mcat, n_operators=5, n_per_operator=30, seed=11,
            true_gamma_by_operator=true_gamma, noise_sigma_log=0.05,
        )
        loader = tsl.TimeStudyLoader(tax, mcat)
        rows = loader.load_batch_dict({k: v for k, v in batch.items() if k != "_ground_truth"}).rows

        outcomes, p_fitted, _ = cf.fit_scope1(tax, mcat, es.MotionParams(), rows)
        import json
        fitted_raw = json.loads(json.dumps(tax.raw))
        gp_by_symbol = {gp["symbol"]: gp for gp in fitted_raw["global_parameters"]}
        for sym, o in outcomes.items():
            if not o.used_default and sym in gp_by_symbol:
                gp_by_symbol[sym]["default"] = o.fitted_value
        tax_fitted = ht.Taxonomy(fitted_raw)

        gamma_fitted, summary, resid_df = cf.fit_operator_gamma(tax_fitted, mcat, p_fitted, rows)
        factory_id = batch["factory_id"]
        true_order = sorted(true_gamma, key=true_gamma.get)
        fitted_order = sorted(true_gamma, key=lambda op: gamma_fitted.get(f"{factory_id}::{op}", 1.0))
        assert true_order == fitted_order, (
            f"rank order not preserved: true={true_order} fitted={fitted_order} "
            f"raw fitted values={gamma_fitted}"
        )

    def test_empty_rows_returns_empty(self, tax, mcat):
        gamma, summary, df = cf.fit_operator_gamma(tax, mcat, es.MotionParams(), [])
        assert gamma == {}
        assert df.empty


# --------------------------------------------------------------------------
# calibrate_all (end-to-end orchestration) + coverage_report
# --------------------------------------------------------------------------

class TestCalibrateAllEndToEnd:
    def test_runs_without_error_and_shapes_are_sane(self, tax, mcat, loaded_rows):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        assert len(result.scope1) == len(cf.SCOPE1_TAXONOMY_SYMBOLS) + len(cf.MOTIONPARAMS_BOUNDS)
        assert isinstance(result.coverage, pd.DataFrame)
        assert not result.coverage.empty
        assert result.fitted_tax_raw is not None
        # fitted taxonomy must still load and compute without error
        tax_fitted = ht.Taxonomy(result.fitted_tax_raw)
        for code in tax_fitted.list_elements():
            tax_fitted.compute_element(code)

    def test_coverage_report_flags_insufficient_symbols(self, tax, mcat, loaded_rows):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        engine_wide = result.coverage[result.coverage["scope"] == "engine_wide"]
        assert (engine_wide["status"] == "INSUFFICIENT").any(), (
            "a 90-observation synthetic batch should not have enough rows to "
            "identify every one of 41 scope-1 symbols -- some must be flagged"
        )
        assert (engine_wide["status"] == "SUFFICIENT").any()

    def test_notes_report_synthetic_provenance(self, tax, mcat, loaded_rows):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        joined = " ".join(result.notes)
        assert "SYNTHETIC" in joined

    def test_operator_gamma_keys_scoped_by_factory(self, tax, mcat, loaded_rows):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        for key in result.operator_gamma:
            assert "::" in key, f"operator gamma key {key!r} must be factory-scoped"


# --------------------------------------------------------------------------
# IP-provenance smoke check
# --------------------------------------------------------------------------

class TestDiagnostics:
    def test_residual_table_covers_all_rows(self, tax, mcat, loaded_rows):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        tax_fitted = ht.Taxonomy(result.fitted_tax_raw)
        resid = cd.residual_table(tax_fitted, mcat, result.fitted_motion_params, loaded_rows)
        assert len(resid) == len(loaded_rows)
        assert (resid["predicted_s"] > 0).all()
        assert (resid["observed_s"] > 0).all()

    def test_error_summary_has_expected_columns(self, tax, mcat, loaded_rows):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        tax_fitted = ht.Taxonomy(result.fitted_tax_raw)
        resid = cd.residual_table(tax_fitted, mcat, result.fitted_motion_params, loaded_rows)
        by_kind = cd.error_summary_by_kind(resid)
        assert {"kind", "n", "MAPE_pct", "RMSE_log", "bias_pct"} <= set(by_kind.columns)
        assert (by_kind["MAPE_pct"] >= 0).all()

    def test_fit_recovers_low_error_on_own_synthetic_data(self, tax, mcat, loaded_rows):
        """Sanity floor: fitting the engine to noise generated FROM the
        engine's own predictions (see generate_synthetic_batch's noise_sigma_log
        default of 0.12) should recover single-digit-to-low-teens MAPE, not
        blow up. This catches a broken fit (e.g. a sign error) that would
        otherwise pass the narrower unit tests above."""
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        tax_fitted = ht.Taxonomy(result.fitted_tax_raw)
        resid = cd.residual_table(tax_fitted, mcat, result.fitted_motion_params, loaded_rows)
        by_kind = cd.error_summary_by_kind(resid)
        assert (by_kind["MAPE_pct"] < 30.0).all(), f"MAPE unexpectedly high: {by_kind}"

    def test_cross_validated_mape_runs_and_is_positive(self, tax, mcat, loaded_rows):
        cv = cd.cross_validated_mape(tax, mcat, loaded_rows, k=3, seed=1)
        assert cv["mean_MAPE_pct"] is not None
        assert cv["mean_MAPE_pct"] > 0
        assert len(cv["folds"]) == 3

    def test_diagnostics_figure_renders(self, tax, mcat, loaded_rows, tmp_path):
        result = cf.calibrate_all(tax, mcat, loaded_rows)
        tax_fitted = ht.Taxonomy(result.fitted_tax_raw)
        resid = cd.residual_table(tax_fitted, mcat, result.fitted_motion_params, loaded_rows)
        by_kind = cd.error_summary_by_kind(resid)
        cv = cd.cross_validated_mape(tax, mcat, loaded_rows, k=3, seed=1)
        out_path = str(tmp_path / "diag.png")
        fig = cd.render_diagnostics_figure(resid, by_kind, result.coverage, cv, out_path)
        import os
        assert os.path.exists(out_path)
        assert os.path.getsize(out_path) > 1000


class TestIPProvenance:
    def test_no_hardcoded_gsd_or_mtm_tables_in_module(self):
        src = open("calibration_fit.py").read()
        banned = ["GSDC", "MTM-1 data card", "MTM Association"]
        # module SHOULD mention MTM in prose/citation context (docstrings) but
        # must not contain a literal TMU-by-distance-class table structure.
        assert "TMU_BY_DISTANCE" not in src
        assert "GB1" not in src and "GB2" not in src  # common MTM Get code names
