"""initial schema

Revision ID: 5d8772f8e2d8
Revises: 
Create Date: 2026-08-29 20:04:23.578269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


# revision identifiers, used by Alembic.
revision: str = '5d8772f8e2d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ie_engineer', 'viewer', 'administrator', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('allowance_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', app.database.JSONBType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_name', 'version', name='uq_allowance_policy_version')
    )
    op.create_index(op.f('ix_allowance_policies_policy_name'), 'allowance_policies', ['policy_name'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('garment_type', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('bundle_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('style_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('prior_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_log_entity_id'), 'change_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_log_style_id'), 'change_log', ['style_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('style_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('bundle_size', sa.Integer(), nullable=False),
    sa.Column('steps', app.database.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_style_id'), 'operations', ['style_id'], unique=False)
    op.create_table('smv_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('style_id', sa.String(), nullable=False),
    sa.Column('st_op_s', sa.Float(), nullable=False),
    sa.Column('st_op_min', sa.Float(), nullable=False),
    sa.Column('bt_op_s', sa.Float(), nullable=False),
    sa.Column('bt_op_min', sa.Float(), nullable=False),
    sa.Column('audit_trail', app.database.JSONBType(), nullable=False),
    sa.Column('allowance_profile', sa.String(), nullable=False),
    sa.Column('allowance_policy_version_id', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('calibration_version', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['allowance_policy_version_id'], ['allowance_policies.id'], ),
    sa.ForeignKeyConstraint(['computed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smv_results_operation_id'), 'smv_results', ['operation_id'], unique=False)
    op.create_index(op.f('ix_smv_results_style_id'), 'smv_results', ['style_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smv_results_style_id'), table_name='smv_results')
    op.drop_index(op.f('ix_smv_results_operation_id'), table_name='smv_results')
    op.drop_table('smv_results')
    op.drop_index(op.f('ix_operations_style_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_change_log_style_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_entity_id'), table_name='change_log')
    op.drop_table('change_log')
    op.drop_table('styles')
    op.drop_index(op.f('ix_allowance_policies_policy_name'), table_name='allowance_policies')
    op.drop_table('allowance_policies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
